### ISSUE TITLE
Server-Timing Headers Read from Browser Cache

### ISSUE THREAD

**Issue by paulcalvano** [w3c/server-timing#13] opened 2017-05-08 21:43 UTC
It seems that Server-Timing headers are swapped into the browsers cache and read when a resource is loaded from cache. If the timing entries are not guaranteed to come from a server, then I imagine that it would present a challenge with aggregating them later on.

I discovered this while testing the Chromium implementation of Server-Timing. I had set up a demo site and adding Server-Timing headers with the RTT from a CDN edge server to the origin. I had added this header for all responses, and found that the same number of Server-Timing headers were returned by performance.getEntriesByType("server"); when I loaded a page as a new visitor and a repeat visitor (with many cached objects). When I examined the timing statistics for some of the cached objects, I found that the TTFB and Content Download time was much faster (ie, microseconds) compared to the reported Server-Timing entries (which were measured in milliseconds).

Should there be any provision, either in the server-timing specification or the browsers where this is implemented, to prevent Server-Timing headers from being counted when a resource is fetched from a browser cache?

**Comment by cvazac** [comment] 2017-05-08 22:09
Because server-timing can be used to pass arbitrary data back to the client, who is to say if that data is still valid or not? I see this as something that consumers of the server-timing API need to be aware of, not necessarily something that needs to be changed. 

Yes, true timing metrics should probably only be "counted once", lest they skew the results.

But if the server wanted to pass a shasum back to the client for the given resource, using a contrived example, that would forever be valid.

**Comment by andreas-marschke** [comment] 2017-05-09 08:44
Sorry if I'm reading this incorrectly but according to the spec a value for a metric could never be a shasum as that isn't allowed per definition:
``` 
metric-value         = 1\*DIGIT [ "." 1\*DIGIT ]
```
Now the implementor _may_ use either the description field or the actual name to convey a shasum or hash of any kind but those should be out of spec and handled as such.

**Comment by nicjansma** [comment] 2017-05-09 14:31
@andreas-marschke The description field was intended to allow arbitrary data, so I don't think using it for the above scenario is necessarily out of spec.

I agree with @paulcalvano that there may be some confusion and careful handling needed for cached resources with regards to ServerTiming.  Not all of the ST entries may be appropriate for cached resources, particularly ST entries with a duration.  But as @cvazac suggests, I could see uses where data from cached ST resources would still be useful, particularly to know other performance characteristics of the resource such as the hash, origin-data-center, origin-cache-status, origin-timestamp, etc.

Hopefully, consumers of ST will fetch the corresponding RT entry and look at hints like `transferSize` or `duration` to know if the ST entry came from a cache hit, but maybe we should make it a bit easier for the consumer?  Getting RT from ST isn't the easiest thing to do because you probably need to match both `name` and `startTime` (in case there are duplicate requests for the same URL) (so `.getEntriesByName()` followed by a `.filter()`).

**Comment by cvazac** [comment] 2017-05-11 20:41
I suggest no spec change because server-timing entries might contain metadata about a resource that is interesting in analytics, regardless of whether the resource was served from browser cache or not. For example, the dimensions and byte count of an image. One might want to compare that data to what actually showed up in the browser, using `offsetHeight`/`offsetWidth` and `*Size` of the `PerformanceResourceTiming` entry.

In addition, there might be relevant prior art in resource-timing. When a resource is served from browser cache, `transferSize === 0`, but `encodedBodySize` and `decodedBodySize` have meaningful values.

**Comment by nicjansma** [comment] 2017-05-19 14:26
>Getting RT from ST isn't the easiest thing to do because you probably need to match both name and startTime (in case there are duplicate requests for the same URL) (so .getEntriesByName() followed by a .filter()).

@cvazac pointed out to me this wouldn't work, as ServerTiming `.startTime` is always `0`.  So if you have multiple ResourceTiming entries with ServerTimings, you can't know which are associated with each other.

**Comment by igrigorik** [comment] 2017-06-13 21:04
Agree that we shouldn't limit ST to network-fetch only. 

We want ST to be aligned with RT: if there is an RT entry for a fetch in the timeline, there should be a corresponding ST entry (if the headers are present). The linking part between RT and ST _is_ tricky today, but let's explore that part of the puzzle in https://github.com/w3c/server-timing/issues/14.

Closing, @paulcalvano feel free to reopen if you disagree.

**Closed by igrigorik** 2017-06-13 21:04 UTC
